the_scene_couch/config/routes.rb
Rails.application.routes.draw do

  # users route
  resources :users do
    # Shallow Nesting : generates the collection actions scoped under the parent, so as to get a sense of the hierarchy, but do not nest the member actions.
    resources :posts, shallow: true
    resources :likes, shallow: true
  end

  # posts route
  resources :posts do
    resources :likes, shallow: true
    resources :users, shallow: true
  end

  # set the root index
  root "posts#index"

  resource :session, only: [:new, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

the_scene_couch/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

the_scene_couch/app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

the_scene_couch/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :user_likes, through: :likes, source: :user 
end

the_scene_couch/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
end

the_scene_couch/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

end

the_scene_couch/app/controllers/likes_controller.rb
class LikesController < ApplicationController
end

the_scene_couch/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_unless_logged_in, except: [:show, :index]
  # before_action :set_user, only: [:new, :edit, :show, :update]
  # before_action :set_user
  helper_method :current_user
  before_action :set_current_user
  before_action :current_user

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all.order("created_at DESC")

    respond_to do |format|
      format.html
      format.json {render json: @posts}
    end
  end


  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    # @post = Post.find(params[:id])
  end


  private

  def redirect_unless_logged_in
      @current_user = current_user

      redirect_to new_session_path unless @current_user
  end

  def post_params
    params.require(:post).permit(:title, :video, :content)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_current_user
    @current_user = current_user
  end
end

the_scene_couch/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(username: params[:user][:username])


    # if the username matches, test the password
    if @user.authenticate(params[:user][:password])
      session[:current_user_id] = @user.id
      redirect_to root_url, :notice => 'Logged In!'
    else
      # examples of how to flash messages:
      # flash[:alert] = "Username or password was incorrect."
      # flash.alert = "Username or password was incorrect."
      # redirect_to new_session_path, notice: "Username or password was incorrect."
      flash.now.alert = "Invalid username or password."
      render "new"
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_url, :notice => "Logged Out"
  end

end

the_scene_couch/app/controllers/users_controller.rb
class UsersController < ApplicationController
  #defining middleware here to run before the action
  #before any action takes place, :{do this action}, [{which methods}]
  # before_action :set_user, only: [:edit, :show, :update]
  # same as: before_action :grab_user, except: [:index, :new, :create, :destroy]
  # before_action :set_user
  before_action :set_current_user
  before_action :current_user

  # index page action
  def index
    @users = User.all

    respond_to do |format|
      format.html
      format.json {render json: @users}
    end
  end

  # show page action
  def show

  end

  # new user action
  def new
    @user = User.new()
  end

  # create user method
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url, :notice => "Successfully signed up!"
    else
      redirect_to new_user_path
    end
  end


  private

  def user_params
    # cleans up the params when we need them
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_current_user
    # instance variable = method made in application_controller.rb
    @current_user = current_user
  end
end

the_scene_couch/app/helpers/application_helper.rb
module ApplicationHelper
end

the_scene_couch/app/helpers/likes_helper.rb
module LikesHelper
end

the_scene_couch/app/helpers/posts_helper.rb
module PostsHelper
end

the_scene_couch/app/helpers/session_helper.rb
module SessionHelper
end

the_scene_couch/app/helpers/users_helper.rb
module UsersHelper
  # inside the views create light logic
  # you have to import them into the controller "helper UsersHelper"
end

the_scene_couch/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>the scene couch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-container">
      <header>
        <div class="banner"></div>
      </header>
      <nav class='navbar'>
        <div class="navbar-menu">
          <div class="navbar-start">
            <a class='navbar-item' href="<%= root_url %>">Home</a>
          </div>
          <div class="navbar-end">
            <% if @current_user %>
            <div class="navbar-item">
              <span class='user-welcome'>welcome <%=@current_user.username%>!  </span>
              <form action="<% session.clear %>">
                <input class='button' type="submit" value="LOG OUT">
              </form>
            </div>
            <% else %>
              <a class='navbar-item' href="/users/new">Sign Up</a>
              <a class='navbar-item' href="/session/new">Sign In</a>
            <% end %>
          </div>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

the_scene_couch/app/views/posts/index.html.erb
<div class="content">
  <h1 class='title'>the scene couch</h1>
  <h1>ALL POSTS</h1>
  <div class="all-posts">
    <% if @current_user %>
      <a href="/users/<%=@current_user.id%>/posts/new">CREATE A NEW POST</a>
    <% end %>

    <% @posts.each do |post| %>
      <div class="card">
        <%= link_to post.title, post %>
        <%= post.video %>
        <%= post.content %>
      </div>
    <% end %>
  </div>
</div>

the_scene_couch/app/views/posts/new.html.erb
<div class="content">
  <h1>NEW POST</h1>
  <div class="input-form">
    <form action="<%=posts_path%>" method="post">
      <input type="hidden" name="authenticity_token" value='<%=form_authenticity_token%>'>
      <input class='input' type="text" name="post[title]" placeholder='title'>
      <input class='input' type="text" name="post[video]" placeholder='video embedded url'>
      <textarea class='textarea' type="textarea" name="post[content]" rows="8" placeholder='review'></textarea>
      <input class='button' type="submit" value="SUBMIT">
    </form>
  </div>
</div>

the_scene_couch/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<div class="content">
  <iframe width="560" height="315" src="<%= @post.video%>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <p><%= @post.content%></p>
</div>

the_scene_couch/app/views/users/index.html.erb
<div class="content">
  <h1>ALL USERS</h1>
  <ul class='users'>
    <% @users.each do |user| %>
      <li><%= user.username %></li>
    <% end %>
  </ul>


  <hr>

  <a href='<%= new_user_path %>'>Sign Up</a>
</div>

the_scene_couch/app/views/users/new.html.erb
<div class="content">
  <h1>SIGN UP</h1>
  <div class="input-form">
    <form action='<%= users_path %>' method='post'>
      <input type="hidden" name="authenticity_token" value='<%=form_authenticity_token%>'>
      <input class='input' type="text" name="user[username]" placeholder='username'>
      <input class='input' type="password" name="user[password]" placeholder='password'>
      <input class='button' type="submit" value="SUBMIT">
    </form>
  </div>
</div>

the_scene_couch/app/views/users/show.html.erb
<div class="content">
  <% if @current_user %>
    <h5>WElcome <%= @current_user.username %></h5>
  <%end%>
</div>